#!/bin/bash

echo "🔥 Firebase Setup Instructions for Kakanga Constructions"
echo "======================================================"
echo ""
echo "1. 🌐 Go to Firebase Console:"
echo "   https://console.firebase.google.com/"
echo ""
echo "2. ➕ Create New Project:"
echo "   - Click 'Create a project'"
echo "   - Name: 'kakanga-constructions' (or your preferred name)"
echo "   - Accept terms and create"
echo ""
echo "3. 🔐 Enable Authentication:"
echo "   - Go to Authentication > Get started"
echo "   - Click 'Sign-in method' tab"
echo "   - Enable 'Email/Password'"
echo ""
echo "4. 🗄️ Enable Firestore:"
echo "   - Go to Firestore Database > Create database"
echo "   - Start in production mode"
echo "   - Choose your region"
echo ""
echo "5. 🔧 Get Configuration:"
echo "   - Go to Project Settings (gear icon)"
echo "   - Scroll to 'Your apps' > Add web app"
echo "   - Name: 'kakanga-web'"
echo "   - Copy the config object"
echo ""
echo "6. 📝 Update .env.local with your values:"
echo "   Replace 'your-api-key', 'your-project-id', etc. with actual values"
echo ""
echo "7. 👤 Create Admin User:"
echo "   - In Firebase Console > Authentication > Users"
echo "   - Click 'Add user'"
echo "   - Email: admin@kakangaconstructions.com"
echo "   - Password: (create a secure password)"
echo ""
echo "8. 🔒 Update Firestore Rules:"
echo "   - Go to Firestore > Rules"
echo "   - Replace with rules from FIREBASE_SETUP.md"
echo ""
echo "✅ After setup, restart your dev server and try:"
echo "   http://localhost:3000/login"
echo "   http://localhost:3000/dashboard"
echo ""

# Check if already configured
if grep -q "your-api-key" .env.local; then
    echo "⚠️  Firebase not configured yet - still has placeholder values"
else
    echo "✅ Firebase appears to be configured"
fi